// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHQrwO3bNQlWyVMAuDfL9G4YejErQhHY',
    appId: '1:159463910979:web:04ce931cb7f09591b7eef6',
    messagingSenderId: '159463910979',
    projectId: 'fir-a7b44',
    authDomain: 'fir-a7b44.firebaseapp.com',
    storageBucket: 'fir-a7b44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCru9Co1Lcxis5PxCsv_DTZSBZb5vFkcUs',
    appId: '1:159463910979:android:05196a4896dbc42eb7eef6',
    messagingSenderId: '159463910979',
    projectId: 'fir-a7b44',
    storageBucket: 'fir-a7b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNd2UwgDnDSiaF4xR-dct5N1Ms9-2UPs',
    appId: '1:159463910979:ios:5c61cbbaf16b611ab7eef6',
    messagingSenderId: '159463910979',
    projectId: 'fir-a7b44',
    storageBucket: 'fir-a7b44.appspot.com',
    iosClientId: '159463910979-mfgjcfgcem84ip7mcobdmqqgllp4leh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNd2UwgDnDSiaF4xR-dct5N1Ms9-2UPs',
    appId: '1:159463910979:ios:5c61cbbaf16b611ab7eef6',
    messagingSenderId: '159463910979',
    projectId: 'fir-a7b44',
    storageBucket: 'fir-a7b44.appspot.com',
    iosClientId: '159463910979-mfgjcfgcem84ip7mcobdmqqgllp4leh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );
}
